-- CloudMetrics: database, warehouse, schemas

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'CloudMetrics dev warehouse';

CREATE DATABASE IF NOT EXISTS CLOUDMETRICS
  COMMENT = 'CloudMetrics analytics';

USE WAREHOUSE DEV_WH;
USE DATABASE CLOUDMETRICS;

CREATE SCHEMA IF NOT EXISTS RAW
  COMMENT = 'Raw Segment, HubSpot, Intercom';

CREATE SCHEMA IF NOT EXISTS STAGING
  COMMENT = 'dbt staging';

CREATE SCHEMA IF NOT EXISTS MARTS
  COMMENT = 'dbt marts';

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE CLOUDMETRICS TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA CLOUDMETRICS.RAW TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA CLOUDMETRICS.STAGING TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA CLOUDMETRICS.MARTS TO ROLE SYSADMIN;

GRANT CREATE TABLE ON SCHEMA CLOUDMETRICS.RAW TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA CLOUDMETRICS.STAGING TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA CLOUDMETRICS.MARTS TO ROLE SYSADMIN;
