-- Keboola Writer Snowflake user
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS KEBOOLA_WRITER;

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE KEBOOLA_WRITER;
GRANT USAGE ON DATABASE CLOUDMETRICS TO ROLE KEBOOLA_WRITER;
GRANT USAGE ON SCHEMA CLOUDMETRICS.RAW TO ROLE KEBOOLA_WRITER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA CLOUDMETRICS.RAW TO ROLE KEBOOLA_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA CLOUDMETRICS.RAW TO ROLE KEBOOLA_WRITER;

-- Set password via Snowflake UI or replace placeholder before running
CREATE USER IF NOT EXISTS KEBOOLA_WRITER
  PASSWORD = 'YOUR_KEBOOLA_PASSWORD'
  LOGIN_NAME = KEBOOLA_WRITER
  DISPLAY_NAME = 'Keboola ELT Writer'
  DEFAULT_ROLE = KEBOOLA_WRITER
  DEFAULT_WAREHOUSE = DEV_WH
  DEFAULT_NAMESPACE = CLOUDMETRICS.RAW
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE KEBOOLA_WRITER TO USER KEBOOLA_WRITER;

-- Verify
SHOW USERS LIKE 'KEBOOLA_WRITER';
SHOW GRANTS TO USER KEBOOLA_WRITER;
