-- dbt grants for SYSADMIN role

USE ROLE ACCOUNTADMIN;

GRANT CREATE VIEW ON SCHEMA CLOUDMETRICS.STAGING TO ROLE SYSADMIN;
GRANT CREATE TABLE ON SCHEMA CLOUDMETRICS.MARTS TO ROLE SYSADMIN;

-- Segment + RAW read access
GRANT USAGE ON SCHEMA CLOUDMETRICS.CLOUDMETRICS_DEMO_API TO ROLE SYSADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA CLOUDMETRICS.CLOUDMETRICS_DEMO_API TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CLOUDMETRICS.CLOUDMETRICS_DEMO_API TO ROLE SYSADMIN;

GRANT SELECT ON ALL TABLES IN SCHEMA CLOUDMETRICS.RAW TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CLOUDMETRICS.RAW TO ROLE SYSADMIN;
