-- List Segment destination tables in CLOUDMETRICS

USE DATABASE CLOUDMETRICS;

SHOW SCHEMAS IN DATABASE CLOUDMETRICS;

SELECT table_schema, table_name, row_count, created
FROM CLOUDMETRICS.INFORMATION_SCHEMA.TABLES
WHERE table_schema NOT IN ('INFORMATION_SCHEMA')
ORDER BY created DESC;

SELECT COUNT(*) AS segment_events_rows FROM CLOUDMETRICS.RAW.SEGMENT_EVENTS;
